---
# supported frameworks: mocha|jest|jasmine
framework: jest

# blocklist:
#   # format: "<filename>##<suit-name>##<suit-name>##<test-name>"
#   - "src/test/api.js"
#   - "src/test/api1.js##this is a test-suite"
#   - "src/test/api2.js##this is a test-suite##this is a test-case"

preRun:
  # set of commands to run before running the tests like `yarn install`, `yarn build`
  command:
    # change the command according to the package manager being used in the repository.
    # For eg, npm ci, yarn install or any other command used to fetch node modules
    - yarn install
    - yarn build
    - yarn run

postMerge:
  # env vars provided at the time of discovering and executing the post-merge tests
  # env:
  #   REPONAME: nexe
  #   AWS_KEY: ${{ secrets.AWS_KEY }}
  # glob-pattern for identifying the test files
  pattern:
    # regex pattern to discover tests to run in case of postMerge
    - "./packages/**/test/*.test.ts"

preMerge:
  pattern:
    # regex pattern to discover tests to run in case of premerge
    - "./packages/**/test/*.test.ts"

postRun:
  # set of commands to run after running the tests
  command:
    - node --version

# path to your custom configuration file required by framework
configFile: jest.config.js

# provide the semantic version of nodejs required for your project
nodeVersion: 16.13.1

# configure whether to smartSelect test-cases. Default true
smartRun: true

# supported tiers: xsmall|small|medium|large|xlarge
# tier: small

# number of parallel instances of containers to spawned to distribute test execution
parallelism: 2

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
version: 1.0
